# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e719e4657ff7911a741b5b4834528f29fa7a6ad9419cda0de653bdba927081812ac32da940069e419e3aef4f96862c12b8e65e8decf45b2e88643177bc1012

test:
  secret_key_base: cfec24ef6cfee0bb0f71337902e091185cd88f03a5f4f78788ccdeb51822a18810a08f4f0884ea4a54bde38aa075148bf15ccc99d651c870168599114fe33bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
